"""edit the queue table

Revision ID: 1ac236415163
Revises: 020cfbc6c497
Create Date: 2026-06-07 15:16:14.768299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac236415163'
down_revision: Union[str, Sequence[str], None] = '020cfbc6c497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('queue_table_patient_id_fkey'), 'queue_table', type_='foreignkey')
    op.drop_column('queue_table', 'patient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_table', sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('queue_table_patient_id_fkey'), 'queue_table', 'patient', ['patient_id'], ['patient_id'])
    # ### end Alembic commands ###
