"""doctor_id col set to null in Patient Table

Revision ID: 5c4658bc50da
Revises: e1c057b18c2a
Create Date: 2026-03-15 22:40:45.155015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4658bc50da'
down_revision: Union[str, Sequence[str], None] = 'e1c057b18c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'docter_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'docter_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
