"""middle add to patient_table

Revision ID: 6d7d0804eb61
Revises: 85c9474e8e9d
Create Date: 2026-07-09 23:50:13.832146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7d0804eb61'
down_revision: Union[str, Sequence[str], None] = '85c9474e8e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('middle_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'middle_name')
    # ### end Alembic commands ###
