"""upate to multple tables

Revision ID: 7b6526bbd55b
Revises: ae76ffb45d5e
Create Date: 2026-06-10 20:24:46.644547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6526bbd55b'
down_revision: Union[str, Sequence[str], None] = 'ae76ffb45d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_table', sa.Column('appointment_type', sa.String(), nullable=False))
    op.drop_constraint(op.f('patient_records_patient_vitals_fkey'), 'patient_records', type_='foreignkey')
    op.drop_column('patient_records', 'patient_vitals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_records', sa.Column('patient_vitals', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('patient_records_patient_vitals_fkey'), 'patient_records', 'patient_vitals', ['patient_vitals'], ['patient_vitals_id'])
    op.drop_column('appointment_table', 'appointment_type')
    # ### end Alembic commands ###
