"""slot_number made nullable

Revision ID: 9acbd5aa0ef9
Revises: 451ae0be3097
Create Date: 2026-08-29 22:16:27.945385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9acbd5aa0ef9'
down_revision: Union[str, Sequence[str], None] = '451ae0be3097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue_table', 'slot_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue_table', 'slot_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
