"""patient vitals update

Revision ID: a22fb831038d
Revises: 196f5a56a697
Create Date: 2026-05-03 18:25:37.468412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22fb831038d'
down_revision: Union[str, Sequence[str], None] = '196f5a56a697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_table')
    op.add_column('patient_vitals', sa.Column('pulse_oximetry', sa.Float(), nullable=False))
    op.add_column('patient_vitals', sa.Column('respiratory_rate', sa.Float(), nullable=False))
    op.add_column('patient_vitals', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('patient_vitals', sa.Column('body_weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_vitals', 'body_weight')
    op.drop_column('patient_vitals', 'height')
    op.drop_column('patient_vitals', 'respiratory_rate')
    op.drop_column('patient_vitals', 'pulse_oximetry')
    op.create_table('queue_table',
    sa.Column('queue_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('queue_id', name=op.f('queue_table_pkey'))
    )
    # ### end Alembic commands ###
